---
version: "3"

env:
  # DOTFILES is the path to where the dotfiles repository has been checked out.
  DOTFILES: "{{ .ROOT_DIR }}"

tasks:
  setup:
    desc: "setup home directory to use these dotfiles"
    cmds:
    # configure git to include git config, attributes and excludes.
    - cmd: "git config --global include.path $DOTFILES/config/git/config"
    - cmd: "git config --global core.attributesfile $DOTFILES/config/git/attributes"
    - cmd: "git config --global core.excludesfile $DOTFILES/config/git/excludes"

    # template a .vimrc into $HOME to include vim/vimrc config.
    - cmd: "cat vim/vimrc.home | envsubst > $HOME/.vimrc"
    - cmd: "mkdir -p $HOME/.vim/pack; ln -s $DOTFILES/vim/pack $HOME/.vim/pack/dotfiles"

    # template a .zshrc into $HOME to include the zsh/zshrc config.
    - cmd: "cat zsh/zshrc.home | envsubst > $HOME/.zshrc"

    # create example .secrets in $HOME if one doesn't exist.
    - cmd: 'if [ ! -f "$HOME/.secrets" ]; then cp $DOTFILES/zsh/secrets.home $HOME/.secrets; fi'
    - cmd: 'chmod 600 $HOME/.secrets'
